### ISSUE TITLE
Table has some unexpected second border

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/underwear.css#57] opened 2018-02-23 11:09 UTC
![table](https://user-images.githubusercontent.com/25042256/36591434-4c7991f0-1892-11e8-9dfa-d3b3bddc5719.png)

Reported by @joltrix

**Comment by warpech** [comment] 2018-02-27 15:01
How to reproduce this? I can't reproduce it on the [demo page](https://starcounter.github.io/underwear.css/).

**Comment by warpech** [comment] 2018-02-27 15:06
The problem of the cell background color should be fixed by: https://github.com/Starcounter/underwear.css/pull/60

**Comment by Joltrix** [comment] 2018-02-28 08:57
I think this was a result of some styling still remaining from before me adding underwear.css

**Comment by warpech** [comment] 2018-02-28 10:06
Closing as not reproducible then. Please reopen if you have some new evidence :)

**Closed by warpech** 2018-02-28 10:06 UTC
